# Generated by Django 6.1 on 2026-08-31 10:02

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('icon_code', models.CharField(default='ph-check-circle', help_text='Phosphor or FA icon class', max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Amenities',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(db_index=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(default='India', max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='destinations/')),
                ('tagline', models.CharField(blank=True, max_length=200, null=True)),
                ('is_popular', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['city'],
            },
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('address', models.TextField()),
                ('star_rating', models.PositiveSmallIntegerField(default=4, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('user_rating', models.DecimalField(decimal_places=1, default=4.5, max_digits=3)),
                ('reviews_count', models.PositiveIntegerField(default=120)),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='hotels/')),
                ('description', models.TextField(blank=True, null=True)),
                ('check_in_time', models.CharField(default='14:00', max_length=20)),
                ('check_out_time', models.CharField(default='11:00', max_length=20)),
                ('free_cancellation', models.BooleanField(default=True)),
                ('breakfast_included_default', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('amenities', models.ManyToManyField(blank=True, related_name='hotels', to='hotels.amenity')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotels', to='hotels.destination')),
            ],
        ),
        migrations.CreateModel(
            name='HotelImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='hotel_gallery/')),
                ('caption', models.CharField(blank=True, max_length=150, null=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='hotels.hotel')),
            ],
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Deluxe Room, Executive Suite', max_length=150)),
                ('bed_type', models.CharField(default='1 King Bed or 2 Twin Beds', max_length=100)),
                ('max_adults', models.PositiveIntegerField(default=2)),
                ('max_children', models.PositiveIntegerField(default=1)),
                ('room_size_sqft', models.PositiveIntegerField(default=320)),
                ('base_price_per_night', models.DecimalField(decimal_places=2, default=3500.0, max_digits=10)),
                ('tax_pct', models.DecimalField(decimal_places=2, default=12.0, max_digits=4)),
                ('free_breakfast', models.BooleanField(default=True)),
                ('free_cancellation', models.BooleanField(default=True)),
                ('cancellation_deadline_hours', models.PositiveIntegerField(default=24)),
                ('total_inventory', models.PositiveIntegerField(default=10)),
                ('room_image', models.ImageField(blank=True, null=True, upload_to='rooms/')),
                ('amenities_summary', models.CharField(default='Free High Speed Wi-Fi, Air Conditioning, Smart TV, Tea/Coffee maker', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='hotels.hotel')),
            ],
        ),
    ]
