# Generated by Django 6.1 on 2026-08-31 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PackageCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('icon_code', models.CharField(default='ph-compass', max_length=50)),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='package_categories/')),
            ],
            options={
                'verbose_name_plural': 'Package Categories',
            },
        ),
        migrations.CreateModel(
            name='HolidayPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=280, unique=True)),
                ('destination_city', models.CharField(max_length=100)),
                ('country', models.CharField(default='India', max_length=100)),
                ('duration_days', models.PositiveIntegerField(default=5)),
                ('duration_nights', models.PositiveIntegerField(default=4)),
                ('starting_price', models.DecimalField(decimal_places=2, default=24999.0, max_digits=10)),
                ('original_price', models.DecimalField(decimal_places=2, default=29999.0, max_digits=10)),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='packages/')),
                ('overview', models.TextField()),
                ('highlights', models.TextField(help_text='Line-separated highlights')),
                ('inclusions', models.TextField(default='Accommodation in 4-Star Hotels\nDaily Buffet Breakfast & Dinner\nAirport Pick & Drop in AC Sedan\nSightseeing Tour as per itinerary\n24/7 On-trip Assistance')),
                ('exclusions', models.TextField(default='Airfare / Train fare unless specified\nPersonal expenses & tips\nActivity / Entrance tickets not mentioned\nTravel Insurance')),
                ('user_rating', models.DecimalField(decimal_places=1, default=4.8, max_digits=3)),
                ('reviews_count', models.PositiveIntegerField(default=84)),
                ('flights_included', models.BooleanField(default=False)),
                ('hotels_included', models.BooleanField(default=True)),
                ('transfers_included', models.BooleanField(default=True)),
                ('meals_included', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='packages', to='packages.packagecategory')),
            ],
        ),
        migrations.CreateModel(
            name='PackageItineraryDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.PositiveIntegerField(default=1)),
                ('title', models.CharField(help_text='e.g. Arrival in Srinagar & Dal Lake Shikara Ride', max_length=200)),
                ('description', models.TextField()),
                ('stay_info', models.CharField(default='Overnight stay at 4-Star Deluxe Hotel', max_length=200)),
                ('meals_info', models.CharField(default='Dinner Included', max_length=150)),
                ('activity_icon', models.CharField(default='ph-map-pin', max_length=50)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itinerary_days', to='packages.holidaypackage')),
            ],
            options={
                'ordering': ['day_number'],
            },
        ),
    ]
