# Generated by Django 6.1 on 2026-08-31 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=4, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='airlines/')),
                ('baggage_policy', models.CharField(default='Cabin: 7kg | Check-in: 15kg', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=4, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('city', models.CharField(db_index=True, max_length=100)),
                ('country', models.CharField(default='India', max_length=100)),
                ('terminal_info', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'ordering': ['city', 'code'],
            },
        ),
        migrations.CreateModel(
            name='FlightSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_number', models.CharField(db_index=True, max_length=20)),
                ('departure_time', models.TimeField()),
                ('arrival_time', models.TimeField()),
                ('duration_minutes', models.PositiveIntegerField(help_text='Flight duration in minutes')),
                ('is_direct', models.BooleanField(default=True)),
                ('stops_count', models.PositiveIntegerField(default=0)),
                ('stop_details', models.CharField(blank=True, help_text='e.g. 1 Stop at BOM (1h 15m)', max_length=150, null=True)),
                ('aircraft_type', models.CharField(default='Airbus A320neo', max_length=100)),
                ('operating_days', models.CharField(default='1,2,3,4,5,6,7', help_text='Comma separated days (1=Mon, 7=Sun)', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('airline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='flights.airline')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrivals', to='flights.airport')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departures', to='flights.airport')),
            ],
        ),
        migrations.CreateModel(
            name='FlightDailyInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_datetime', models.DateTimeField(db_index=True)),
                ('arrival_datetime', models.DateTimeField()),
                ('economy_price', models.DecimalField(decimal_places=2, default=4500.0, max_digits=10)),
                ('business_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('economy_seats_available', models.PositiveIntegerField(default=120)),
                ('business_seats_available', models.PositiveIntegerField(default=12)),
                ('refundable', models.BooleanField(default=True)),
                ('cancellation_fee', models.DecimalField(decimal_places=2, default=1500.0, max_digits=10)),
                ('free_meal', models.BooleanField(default=False)),
                ('status', models.CharField(default='ON_TIME', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='flights.flightschedule')),
            ],
            options={
                'ordering': ['departure_datetime', 'economy_price'],
            },
        ),
        migrations.CreateModel(
            name='FlightSeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.CharField(max_length=5)),
                ('cabin_class', models.CharField(choices=[('ECONOMY', 'Economy'), ('PREMIUM_ECONOMY', 'Premium Economy'), ('BUSINESS', 'Business'), ('FIRST', 'First Class')], default='ECONOMY', max_length=20)),
                ('row', models.PositiveIntegerField(default=1)),
                ('column', models.CharField(default='A', max_length=1)),
                ('is_window', models.BooleanField(default=False)),
                ('is_aisle', models.BooleanField(default=False)),
                ('is_extra_legroom', models.BooleanField(default=False)),
                ('seat_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('is_booked', models.BooleanField(default=False)),
                ('flight_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='flights.flightdailyinstance')),
            ],
            options={
                'ordering': ['row', 'column'],
                'unique_together': {('flight_instance', 'seat_number')},
            },
        ),
    ]
